{% set name = "yaqc-qtpy" %}
{% set version = "2022.4.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/yaqc-qtpy-{{ version }}.tar.gz
  sha256: a69b504c5e301406eda82aae39f46b4261527b77f1a0481ac18dd616433b0e32

build:
  script_env:
    - QT_QPA_PLATFORM=offscreen
  number: 0
  noarch: python
  entry_points:
    - yaqc-qtpy=yaqc_qtpy.__main__:main
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pyside2
    - qtpy
    - yaqc
    - flit
    - python >=3.7
  run:
    - appdirs
    - click
    - entrypoints
    - numpy
    - pyside2
    - python >=3.7
    - qtconsole
    - qtpy
    - qtypes >=2022.2.0
    - yaq-traits
    - yaqc
    - yaqd-control
    - yaqd-core >=2020.06.3
    - pyqtgraph

test:
  imports:
    - yaqc_qtpy
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://yaq.fyi
  summary: Tooling for building simple yaq clients using qtpy.
  dev_url: https://gitlab.com/yaq/yaqc-qtpy
  license: LGPL-3.0-only
  license_file: LICENSE

extra:
  recipe-maintainers:
    - untzag
    - ksunden
