{% set name = "yaqc-qtpy" %}
{% set version = "2022.6.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/yaqc-qtpy-{{ version }}.tar.gz
  sha256: 6a6b73fb3179882bc46a18a1de9fc6c8ced2fffb8d0f5e00ed816a8d598a4ead

build:
  script_env:
    - QT_QPA_PLATFORM=offscreen
  number: 2
  entry_points:
    - yaqc-qtpy=yaqc_qtpy.__main__:main
  osx_is_app: true

requirements:
  host:
    - pyside2
    - qtpy
    - yaqc
    - flit
    - python
  run:
    - appdirs
    - click
    - entrypoints
    - numpy
    - pyside2
    - python
    - qtconsole
    - qtpy
    - qtypes >=2022.6.0
    - yaq-traits
    - yaqc
    - yaqd-control
    - yaqd-core
    - pyqtgraph
    - menuinst  # [win]

test:
  imports:
    - yaqc_qtpy
  commands:
    - pip check
  requires:
    - pip

app:
  entry: yaqc-qtpy
  icon: logo.png
  summary: General purpose graphical client for yaq.
  type: desk

about:
  home: https://yaq.fyi
  summary: Tooling for building simple yaq clients using qtpy.
  dev_url: https://gitlab.com/yaq/yaqc-qtpy
  license: LGPL-3.0-only
  license_file: LICENSE

extra:
  recipe-maintainers:
    - untzag
    - ksunden
